name: Realse Mah

on:
  push:
    tags: [ 'v*' ]

jobs:
  build:

    name: Release to Github Release Page
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant Execute Permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew buildCiJar

      - name: Get Tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Generate Line Temp File
        run: "cat CHANGELOG.md | grep -n '## \\\\' | cut -d: -f1 | head -n 2 >> line.tmp"

      - name: Generate Release Log
        run: "cat CHANGELOG.md | head -n $((`tail -n 1 line.tmp`-1)) | tail -n +`head -n 1 line.tmp` >> release.log"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          tag_name: ${{ github.ref }}
          release_name: mirai-api-http-${{ steps.tag.outputs.tag }}
          body_path: release.log
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mirai-api-http/build/ci/mirai-api-http.jar
          asset_name: mirai-api-http-${{ steps.tag.outputs.tag }}.mirai.jar
          asset_content_type: application/zip
#      - name: Gradle publishPlugin
#        run: >
#          ./gradlew publishPlugin --info
#          -Dbintray.user=${{ secrets.BINTRAY_USER }} -Pbintray.user=${{ secrets.BINTRAY_USER }}
#          -Dbintray.key=${{ secrets.BINTRAY_KEY }} -Pbintray.key=${{ secrets.BINTRAY_KEY }}
